### PR TITLE
feat: genAI urdf parser

### LINKED ISSUE #69: Robot description (URDF) service
**Objective**  
The goal of this task is to explore the feasibility of feeding URDF robot data into Large Language Models (LLMs) and to implement a service within `rai_whoami`.

**Proposed Steps**  
1. Evaluate how well the model interprets the URDF format.
2. Determine whether the model can extract significant and useful information from it.
3. If successful, implement a URDF service within `rai_whoami` that hosts URDF-based textual information for use by other nodes.

### PR DESCRIPTION
**Pull request by maciejmajek**
## Purpose

URDF proves to be a great source of information about robot's links and joints. 

## Proposed Changes

Implements #69 

## Issues

Closes #69 

## Testing

Went through https://github.com/RobotecAI/rai/blob/feat/urdf-parser/docs/create_robots_whoami.md

### CODE REVIEW

**Review by adamdbrw — COMMENTED** [review]
Nice, but please use os.path.join for portability

**Comment by maciejmajek** [comment]
Sure. Let me refactor this script in the next PR.

**Review by adamdbrw — APPROVED** [review]
Approved! Nice work. Raise an issue for portability of this script please

**Comment by maciejmajek** [comment]
aforementioned issue https://github.com/RobotecAI/rai/issues/261

**Pull request merged**
